name: Build iOS app with Flutter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'
        
    - name: Install dependencies
      run: flutter pub get

    - name: Install Apple Certificate
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: "temporary_password"
      run: |
        # Create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security set-keychain-settings -t 3600 -l build.keychain

        # Import certificate to keychain
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output certificate.p12
        security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign

        # Apply provisioning profile
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output build.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp build.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    - name: Build iOS
      run: |
        flutter build ios --release --no-codesign
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ios-build
        path: ios/build/